etl:
  use_spark: True
  train_size: 0.75
  split_rand: 15
model:
  tool: 'tensorflow'
  architect: 'covidnet'
  name: 'COVIDNet-CXR-Small-test'
  torch:
    transfer_learning: True
    continue_learning: False
  tensorflow:
    weightspath: './model/COVIDNet-CXR-Small-test'
    metaname: 'model.meta'
    ckptname: 'COVIDNet-CXR-Small-test-9'
    in_tensorname: 'input_1:0'
    out_tensorname: 'dense_3/Softmax:0'
    logit_tensorname: 'dense_3/MatMul:0'
    label_tensorname: 'dense_3_target:0'
    weights_tensorname: 'dense_3_sample_weights:0'
data:
  data_path: './data/'
  crop_top: 0.05
  image_size: 224
train:
  display_step: 1
  epochs: 4
  learning_rate: 0.0002
  lr_decay:
    step_size: 7
    gamma: 0.1
  batch_size: 32
  sample_weight_covid: 0.33
  loss_weights:
    covid: 5
    normal: 1
    pneumonia: 1
evaluate:
  dir_prefix: './output/'
visual:
  feature:
    example_num: 5
    img_size_inch: 6