etl:
  data_path: './data/'
  crop_top: 0.05
  image_size: 480
  use_spark: True
  use_segmentation: True
  use_CLAHE: True
  CLAHE_clip_limit: 2.0
  CLAHE_tile_size: 8
  train_size: 0.8
  split_rand: 15
model:
  tool: 'pytorch'
  architect: 'resnet18'
  name: 'resnet18.iter2.480'
  torch:
    in_channel: 1
    continue_learning: False
    transfer_learning: True
  tensorflow:
    weightspath: './model/COVIDNet-CXR-Small-test'
    metaname: 'model.meta'
    ckptname: 'COVIDNet-CXR-Small-test-9'
    in_tensorname: 'input_1:0'
    out_tensorname: 'dense_3/Softmax:0'
    logit_tensorname: 'dense_3/MatMul:0'
    label_tensorname: 'dense_3_target:0'
    weights_tensorname: 'dense_3_sample_weights:0'
train:
  display_step: 1
  epochs: 3
  learning_rate: 0.00003
  lr_decay:
    step_size: 7
    gamma: 0.1
  batch_size: 32
  sample_weight_covid: 0.33
  loss_weights:
    covid: 5
    normal: 1
    pneumonia: 1
evaluate:
  dir_prefix: './output/'
visual:
  feature:
    example_num: 5
    img_size_inch: 6
    save_path: './diag/'
  transform:
    example_num: 5
    img_size_inch: 5
    save_path: './diag/'
