model:
  tool: 'torch'
  name: 'ResNet-50-test'
  tensorflow:
    weightspath: './model/COVIDNet-CXR-Small'
    metaname: 'model.meta'
    ckptname: 'C:/Users/conno/OMSCS/CSE6250/project/model/COVIDNet-CXR-Small/model-1697'
    in_tensorname: 'input_1:0'
    out_tensorname: 'dense_3/Softmax:0'
    logit_tensorname: 'dense_3/MatMul:0'
    label_tensorname: 'dense_3_target:0'
    weights_tensorname: 'dense_3_sample_weights:0'
data:
  data_path: './data/'
  output_path: './output/'
  crop_top: 0.05
  image_size: 224
train:
  display_step: 1
  epochs: 3
  learning_rate: 0.0006
  lr_decay:
    step_size: 7
    gamma: 0.1
  batch_size: 32
  batch_weight_covid: 0.3
  class_weights:
    covid: 4
    normal: 1
    pneumonia: 1
  labelmap:
    covid: 0
    normal: 1
    pneumonia: 2
evaluate:
  dir_prefix: './output/'